### PR TITLE
Include Compensation Clarification

### PR DESCRIPTION
**Pull request by pentargency**
Just a small modification to the task instructions to ensure that candidates are not confused by the nature of the task or the potential results of completing it on their own time.

### CODE REVIEW

**Comment by Geoffrey-D** [comment]
@iHiD @ErikSchierboom @SleeplessByte please have the decency to either merge this PR, include a compensation plan or remove this project. Just because you can abuse on candidates doesn't mean you should

**Review by mindaugasw — APPROVED** [review]
Well done, the readme looks much more complete now 👍

**Comment by SleeplessByte** [comment]
@Geoffrey-D i don't know why you tagged me. I do not work for Exercism, nor do I have merge rights.

I do however review submissions from applicants, on a voluntary basis -- in the same way that thousands of other volunteers review submissions on the platform itself to help other (aspiring) programmers get better.

Currently i spend about two hours per applicant creating a 15+ page document of feedback on their submission, full with links and comments about what I liked and what parts of their submission could be improved, so that, even if they don't qualify, they can walk away with something, hopefully, valuable.

Would you like me to stop doing that?

**Comment by 3150512415** [comment]
@SleeplessByte so you are doing the job of a recruiter/manager for free? Of course you should stop doing that.
They made their bed. Let them lie in it.

**Comment by SleeplessByte** [comment]
I don't do the job of recruitment manager.

I offered to review the applications and make no decision about the outcome. When I offered it to Exercism I said something along the lines of "if an applicant spents hours applying, I would like to return the favour so they walk away with something worthwhile".

The entire review gets back to the applicant and they are free to ask me anything about anything (which many of them do) -- providing free mentorship to anyone who has applied.

This does not mean I agree or disagree with the morals or ethics of the project. I offered to Exercism what I wish other companies had done for me in the past.

**Comment by Geoffrey-D** [comment]
> @Geoffrey-D i don't know why you tagged me. I do not work for Exercism, nor do I have merge rights.
> 
> I do however review submissions from applicants, on a voluntary basis -- in the same way that thousands of other volunteers review submissions on the platform itself to help other (aspiring) programmers get better.
> 
> Currently i spend about two hours per applicant creating a 15+ page document of feedback on their submission, full with links and comments about what I liked and what parts of their submission could be improved, so that, even if they don't qualify, they can walk away with something, hopefully, valuable.
> 
> Would you like me to stop doing that?

You claim not to work for them (I quote you: "I do not work for Exercism" https://github.com/exercism/hiring-frontend-developer/pull/31#issuecomment-1110855510)

yet:
- you know how their recruitment process works: "No points are deducted for submitting Vanilla CSS" in https://github.com/exercism/hiring-frontend-developer/pull/44#discussion_r859654841 
- know their API: "The provided API does the filtering when used correctly." in https://github.com/exercism/hiring-frontend-developer/pull/44#discussion_r859660096
- say "we" when talking about the company and know this recruitment process: "We try to, but it's not part of the requirement of this job application." https://github.com/exercism/hiring-frontend-developer/pull/44#discussion_r859660465
- know their expectations: "No marathon running is required"  https://github.com/exercism/hiring-frontend-developer/pull/44#discussion_r859653510

And you expect people just to believe that you are just doing some "review submissions [...] on a voluntary basis" ?

**Comment by SleeplessByte** [comment]
I don't expect you to believe it, but that doesn't make it more or less true.

I am one of top contributors (number 11 here: https://exercism.org/contributing/contributors?) which makes it probably reasonable that I have some knowledge of how this company operates.

Exercism holds weekly community calls where everything is discussed openly (and anyone can join, employee, contributors, students) and thus the interview process was also shared. 

I've never been paid by Exercism or Exercism's founders. I've not worked for Exercism or Exercism's founders. Your belief doesn't change these facts :)

**Comment by iHiD** [comment]
> They made their bed. Let them lie in it.

I'm writing a blog post to reply to all this at the moment, but I'd to be clear @SleeplessByte doesn't work for Exercism and isn't paid by Exercism, but rather kindly volunteers his valuable time helping the project. This is true of thousands of other people too...  https://exercism.org/contributing/contributors

You maybe missed that Exercism is fundamentally a community of volunteers building something together to help others. 95% of our codebase is created by volunteers. People like @SleeplessByte are the bedrock of how Exercism works. Until we started hiring a month ago, we had one full time employee, me working when I can on the project, and a couple of others we've contracted out work too previously. We now have two (non-technical) full time employees as well.

We're also free, open-source and not-for-profit. We don't have shares or shareholders - no-one is benefiting from anyone else's work in this. We're working together (and have done for many years) to try and help others.

You may also not be aware, but the CSS and functionality in this PR is already in Exercism's codebase and are used in multiple places, so we're not trying to get people to implement improvements to Exercism for free.

I'll follow up in a blog post, but as someone has now turned the conversation towards questioning one of our community's honestly, I'm stepping in to stop this.

**Pull request closed without merging**
